services:
  db:
    container_name: psynth-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: psynth
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d psynth -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - api-net

  app:
    container_name: psynth-auth-service-container
    build: .
    ports:
      - "3050:3050"
    environment:
      POSTGRESQL_HOST: db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USER: postgres
      POSTGRESQL_DATABASE: psynth
      POSTGRESQL_PASSWORD: password
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - api-net

networks:
  api-net:


volumes:
  pgdata:
