FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY src/ src/
COPY tsconfig.json index.d.ts ./
COPY config/ config/
COPY drizzle/ drizzle/
COPY drizzle.config.ts ./
RUN npm run build
EXPOSE 3050
CMD ["npm", "start"]
